branches:
  only:
  - master
language: csharp
solution: Plutus.sln
mono: none
dotnet: 2.1
script:
 - dotnet restore
 - dotnet test Plutus.Tests.Unit/Plutus.Tests.Unit.csproj -v n
services:
  - redis-server
